on:
  push:
    branches:
      - dev
name: 🚀 Deploy ke server trial
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: dokumen.bgiapp.web.id
        username: ${{ secrets.dev_ftp_username }}
        password: ${{ secrets.dev_ftp_password }}
        server-dir: /public_html/
